name: midtrans-gateway
services:
  midtrans-gateway:
    container_name: midtrans-gateway
    build: .
    image: midtrans-gateway:1.0.0
    env_file:
      - .env
    cpus: 0.1
    mem_limit: 256m
    mem_reservation: 64m
    restart: unless-stopped
    networks:
      - flexeet-network

networks:
  flexeet-network:
    external: true
